---
# Ansible demo which creates an openstack instance and configures a webserver
- name: Create and configure demo VM
  hosts: ansible-demo # Hostname that ansible connects to
  gather_facts: false # Disable running setup module which will fail before VM exists

  pre_tasks:
    - name: Import cloud specific vars
      include_vars:
        file: "{{ cloud | default('nebula') }}.yml"

  roles:
    - openstack-instance # Create a vm if it doesn't exist
    - demo-webserver     # Configure the vm as a webserver
...
