---
# Basic demo of using Ansible to create a virtual machine on OpenStack clouds.
#
# You'll need to download and source your credentials before this will work:
#
- name: Create virtual machine on and OpenStack cloud
  hosts: localhost # The OpenStack modules run on your local machine.
  connection: local

  vars:
    # These need changing
    your_name: "jenkins"
    demo_image: centos-7
    demo_flavor: sonera.linux.tiny
    # You can leave these
    demo_key: "{{your_name}}"
    demo_sg: demo-sg-{{your_name}}
    demo_security_groups: default,{{ demo_sg }} # don't add spaces here!

  tasks:
    - name: Create security group
      os_security_group:
        name={{ demo_sg }}

    - name: Add rule to security group to allow http from the internet
      os_security_group_rule:
        security_group: "{{ demo_sg }}"
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: Add rule to security group to ssh from current system
      os_security_group_rule:
        security_group: "{{ demo_sg }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ ansible_default_ipv4.address }}/32"

    - name: Create a virtual machine
      register: result
      os_server:
        name: ansible-demo-{{ your_name }}
        image: "{{ demo_image }}"
        flavor: "{{ demo_flavor }}"
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
        auto_ip: yes

      #- os_server_facts:
      #  server: ansible-demo-{{ your_name }}
      # - debug:
      #  var: openstack_servers

    - name: Create a virtual machine
      register: result
      os_server:
        name: ansible-demo-{{ your_name }}
        image: "{{ demo_image }}"
        flavor: "{{ demo_flavor }}"
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
      until: (result.openstack is defined) and (result.openstack.networks.values()[0] | length > 1)
      delay: 20
      retries: 50 

    - name: Store the auto-allocated floating IP address
      set_fact: floating_ip={{ result.openstack.networks.values()[0][1] }}
    - name: Add new host to inventory
      add_host: name={{ floating_ip }} groups=new
    - name: clear ssh known_hosts
      known_hosts: name={{ floating_ip }} state=absent
      when: result | changed
    - name: Wait for instance to be ready
      wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH delay=5

- name: Configure demo host
  hosts: new
  remote_user: centos
  become: yes  # sudo to root
  vars:
    demo_greeting: "Hello from OpenStack!"

  tasks:
   - name: Configure DNS
     template: src=templates/resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644

   - name: Install a webserver
     yum: name=httpd state=present

   - name: Deploy demo web page
     template: src=templates/demo.html.j2 dest=/var/www/html/index.html owner=apache group=apache mode=0644

   - name: Install firewalld
     yum: name=firewalld state=present

   - name: Start firewalld
     service: name=firewalld state=started enabled=yes sleep=10

   - name: Wait for firewalld
     pause: seconds=30

   - name: Configure firewalld for ssh
     firewalld: service=ssh permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Configure firewalld for http
     firewalld: service=http permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Start apache
     service: name=httpd state=started enabled=yes

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted sleep=5
     
