---
# These will vary from cloud to cloud and probably need overriding in
# group_vars
demo_image: centos-7
demo_flavor: sonera.linux.tiny

# These don't need changing
your_name: "{{ lookup('env', 'USERNAME') }}"
demo_hostname: "ansible-demo-{{ your_name }}"
demo_key: "{{your_name}}"
demo_sg: demo-sg-{{your_name}}
demo_security_groups: default,{{ demo_sg }} # don't add spaces here!
demo_net_name: "{{ lookup('env', 'OS_PROJECT_NAME') }}-net"
demo_greeting: "Hello from OpenStack!"
...
