- block:
  - name: Install a webserver
    yum:
      name: httpd
      state: present

  - name: Deploy demo web page
    template:
      src: templates/demo.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache
      mode: 0644

  - name: Install firewalld
    yum:
      name: firewalld
      state: present

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
    register: firewall_started

  - name: Configure firewalld for ssh
    firewalld:
      service: ssh
      permanent: true
      immediate: true
      state: enabled

  - name: Configure firewalld for http
    firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled

  - name: Start apache
    service:
      name: httpd
      state: started
      enabled: yes

  become: yes  # sudo to root
  # End of block

- name: The webserver is configured
  debug:
    msg: "http://{{ ansible_host }}/"
...
