---
- block: # We use a block to run several tasks on localhost ... see the end of the block
  - name: Gather facts from localhost for the initial part of the playbook
    setup:

  - name: Create security group
    os_security_group:
      name: "{{ demo_sg }}"

  - name: Add rule to security group to allow http from the internet
    os_security_group_rule:
      security_group: "{{ demo_sg }}"
      protocol: tcp
      port_range_min: 80
      port_range_max: 80
      remote_ip_prefix: 0.0.0.0/0

  - name: Get current system public IP
    ipify_facts:

  - name: Add rule to security group to ssh from current system
    os_security_group_rule:
      security_group: "{{ demo_sg }}"
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: "{{ ipify_public_ip }}/32"

  - name: Create a virtual machine
    os_server:
      name: "{{ demo_hostname }}"
      image: "{{ demo_image }}"
      flavor: "{{ demo_flavor }}"
      key_name: "{{ demo_key }}"
      security_groups: "{{ demo_security_groups | default(omit) }}"
      availability_zone: "{{ demo_availability_zone | default(omit) }}"
      network: "{{ demo_net_name | default(omit) }}"
      userdata: "{{ demo_userdata | default(omit) }}"
    register: create_instance

  - name: Set inventory_hostname to the new floating IP address
    set_fact:
      ansible_host: "{{ create_instance.server.accessIPv4 }}"

  - name: Clear ssh known_hosts
    known_hosts:
      name: "{{ ansible_host }}"
      state: absent
    when: create_instance | changed
    ignore_errors: true # This non-essential task tends to fail

  - name: Wait for instance to be ready
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      search_regex: OpenSSH
    when: create_instance | changed

    # Without some short pause, the next task that requires an SSH connection to the
    # remote host will fail.
  - name: Wait for the ssh connection to settle
    pause:
      seconds: 10
    when: create_instance | changed

  delegate_to: localhost
  connection: local # Don't try to ssh to localhost
  # End of block

# Now the Virtual machine is up we re-run setup so after this role is complete
# other tasks can use the host as normal

- name: Work round python3 Ansible bug
  import_tasks: python3-fix.yml

- name: Re-run setup against the new vm
  setup:
...
